#!/usr/bin/env python3
"""Generate one deterministic Sv32/U-mode lock-step program.

The fixed M-mode prologue creates a two-level Sv32 map, enters a user RXU
superpage, and maps one user RW page.  The generated body then performs only
aligned accesses within that page plus RV32I ALU operations.  It finishes by
an ECALL back to M-mode, where the handler checks that fetch set A and data
access set both A and D.  This intentionally complements gen.py: that legacy
corpus remains a simple linear M-mode instruction stream.
"""

import argparse
import random
from pathlib import Path


REGS = tuple(f"x{i}" for i in range(6, 12))


def user_instruction(rng: random.Random) -> str:
    """Return one safe RV32I operation for the mapped user data page."""
    rd = rng.choice(REGS)
    rs1 = rng.choice(REGS)
    rs2 = rng.choice(REGS)
    kind = rng.randrange(10)
    if kind == 0:
        return f"    addi  {rd}, {rs1}, {rng.randrange(-2048, 2048)}"
    if kind == 1:
        return f"    xori  {rd}, {rs1}, {rng.randrange(-2048, 2048)}"
    if kind == 2:
        return f"    andi  {rd}, {rs1}, {rng.randrange(-2048, 2048)}"
    if kind == 3:
        return f"    ori   {rd}, {rs1}, {rng.randrange(-2048, 2048)}"
    if kind == 4:
        return f"    {rng.choice(('add', 'xor', 'or', 'and', 'slt'))} {rd}, {rs1}, {rs2}"
    if kind == 5:
        return f"    {rng.choice(('slli', 'srli', 'srai'))} {rd}, {rs1}, {rng.randrange(32)}"
    offset = 4 * rng.randrange(256)
    if kind < 8:
        return f"    lw    {rd}, {offset}(x5)"
    return f"    sw    {rs2}, {offset}(x5)"


def program(seed: int, count: int) -> str:
    rng = random.Random(seed)
    body = "\n".join(user_instruction(rng) for _ in range(count))
    return f"""# Generated by sim/testgen/sv32.py --seed {seed} --count {count}.
# Do not edit: change the generator and preserve the seed in a failing report.
    .section .text.init
    .globl _start
_start:
    la    x1, m_handler
    csrw  mtvec, x1

    # Keep tables beyond the largest supported generated code image.  User
    # code (VPN1=1) is an RXU superpage; VPN1=2 points to the L0 data table.
    li    x1, 0x80040000
    li    x2, 0x2000001b          # 0x00400000 -> 0x80000000, V|R|X|U
    sw    x2, 4(x1)
    li    x2, 0x20010401          # L0 table at 0x80041000
    sw    x2, 8(x1)
    li    x1, 0x80041000
    li    x2, 0x20010817          # 0x00801000 -> 0x80042000, V|R|W|U
    sw    x2, 4(x1)

    li    x1, 0x80080040          # Sv32, root PPN 0x80040
    csrw  satp, x1
    la    x1, u_entry
    li    x2, 0x80400000          # physical -> virtual code mapping delta
    add   x1, x1, x2
    csrw  mepc, x1
    li    x1, 0x1800
    csrc  mstatus, x1             # MPP = U
    mret

u_entry:
    li    x5, 0x00801000          # translated user data base
    sw    x0, 0(x5)                # guarantee a data walk with A and D set
    lw    x6, 0(x5)
{body}
    ecall                          # non-delegated U ECALL -> M handler
1:  j     1b

m_handler:
    csrr  x5, mcause
    li    x6, 8
    bne   x5, x6, fail1
    # Fetch through the RXU superpage must set A using the ibus walker.
    li    x5, 0x80040004
    lw    x5, 0(x5)
    andi  x5, x5, 0x40
    li    x6, 0x40
    bne   x5, x6, fail2
    # The initial translated store must set both A and D on the L0 leaf.
    li    x5, 0x80041004
    lw    x5, 0(x5)
    andi  x5, x5, 0xc0
    li    x6, 0xc0
    bne   x5, x6, fail3
    li    x5, 0x00100000
    li    x6, 0x5555
    sw    x6, 0(x5)
2:  j     2b

fail1: li x7, 1; j fail
fail2: li x7, 2; j fail
fail3: li x7, 3; j fail
fail:
    li    x5, 0x00100000
    slli  x7, x7, 16
    li    x6, 0x3333
    or    x7, x7, x6
    sw    x7, 0(x5)
3:  j     3b
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--seed", type=int, required=True)
    ap.add_argument("--count", type=int, required=True)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()
    if args.count <= 0:
        ap.error("--count must be positive")
    if args.count > 60000:
        ap.error("--count must not exceed 60000 (keeps code below page tables)")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(program(args.seed, args.count), encoding="utf-8")


if __name__ == "__main__":
    main()
