#!/usr/bin/env python3
"""Flatten aXcore's small SystemVerilog package for Yosys's Verilog frontend.

The checked-in RTL intentionally uses a package for type-safe interfaces.
Current upstream Yosys still rejects `import` in this project configuration, so
the FPGA build creates one disposable source file with equivalent widths and
constants. This script never changes the authored RTL.
"""
from pathlib import Path
import re
import sys

if len(sys.argv) < 3:
    raise SystemExit(f"usage: {sys.argv[0]} OUTPUT.sv SOURCE.sv [...]")

TYPE_REPLACEMENTS = {
    "axcore_pkg::imm_sel_e": "logic [2:0]",
    "axcore_pkg::opa_sel_e": "logic [1:0]",
    "axcore_pkg::opb_sel_e": "logic [0:0]",
    "axcore_pkg::alu_op_t": "logic [3:0]",
    "axcore_pkg::wb_sel_e": "logic [1:0]",
    "axcore_pkg::mem_op_e": "logic [1:0]",
    "axcore_pkg::br_sel_e": "logic [1:0]",
    "axcore_pkg::csr_op_e": "logic [1:0]",
    "axcore_pkg::sys_e": "logic [2:0]",
}
BARE_TYPE_REPLACEMENTS = {
    "imm_sel_e": "logic [2:0]",
    "opa_sel_e": "logic [1:0]",
    "opb_sel_e": "logic [0:0]",
    "alu_op_t": "logic [3:0]",
    "wb_sel_e": "logic [1:0]",
    "mem_op_e": "logic [1:0]",
    "br_sel_e": "logic [1:0]",
    "csr_op_e": "logic [1:0]",
    "sys_e": "logic [2:0]",
}
SYMBOLS = (
    "IMM_I", "IMM_S", "IMM_B", "IMM_U", "IMM_J",
    "OPA_RS1", "OPA_PC", "OPA_ZERO", "OPB_RS2", "OPB_IMM",
    "WB_ALU", "WB_MEM", "WB_PC4", "WB_CSR",
    "MEM_NONE", "MEM_LOAD", "MEM_STORE",
    "BR_NONE", "BR_COND", "BR_JAL", "BR_JALR",
    "CSR_NONE", "CSR_RW", "CSR_RS", "CSR_RC",
    "SYS_NONE", "SYS_ECALL", "SYS_EBREAK", "SYS_MRET", "SYS_SRET",
    "SYS_WFI", "SYS_FENCE_I", "SYS_SFENCE",
    "ALU_ADD", "ALU_SUB", "ALU_SLL", "ALU_SLT", "ALU_SLTU", "ALU_XOR",
    "ALU_SRL", "ALU_SRA", "ALU_OR", "ALU_AND",
)

DEFINES = """// Generated by rtl/fpga/prepare_synth.py; do not edit.
`define IMM_I 3'd0
`define IMM_S 3'd1
`define IMM_B 3'd2
`define IMM_U 3'd3
`define IMM_J 3'd4
`define OPA_RS1 2'd0
`define OPA_PC 2'd1
`define OPA_ZERO 2'd2
`define OPB_RS2 1'd0
`define OPB_IMM 1'd1
`define WB_ALU 2'd0
`define WB_MEM 2'd1
`define WB_PC4 2'd2
`define WB_CSR 2'd3
`define MEM_NONE 2'd0
`define MEM_LOAD 2'd1
`define MEM_STORE 2'd2
`define BR_NONE 2'd0
`define BR_COND 2'd1
`define BR_JAL 2'd2
`define BR_JALR 2'd3
`define CSR_NONE 2'd0
`define CSR_RW 2'd1
`define CSR_RS 2'd2
`define CSR_RC 2'd3
`define SYS_NONE 3'd0
`define SYS_ECALL 3'd1
`define SYS_EBREAK 3'd2
`define SYS_MRET 3'd3
`define SYS_SRET 3'd4
`define SYS_WFI 3'd5
`define SYS_FENCE_I 3'd6
`define SYS_SFENCE 3'd7
`define ALU_ADD 4'b0000
`define ALU_SUB 4'b1000
`define ALU_SLL 4'b0001
`define ALU_SLT 4'b0010
`define ALU_SLTU 4'b0011
`define ALU_XOR 4'b0100
`define ALU_SRL 4'b0101
`define ALU_SRA 4'b1101
`define ALU_OR 4'b0110
`define ALU_AND 4'b0111
"""

parts = [DEFINES]
for source_arg in sys.argv[2:]:
    source = Path(source_arg)
    if source.name == "axcore_pkg.sv":
        continue
    text = source.read_text()
    text = text.replace("import axcore_pkg::*;", "")
    for original, replacement in TYPE_REPLACEMENTS.items():
        text = text.replace(original, replacement)
    for original, replacement in BARE_TYPE_REPLACEMENTS.items():
        text = re.sub(rf"\b{original}\b", replacement, text)
    for symbol in SYMBOLS:
        text = re.sub(rf"\b{symbol}\b", f"`{symbol}", text)
    if "axcore_pkg::" in text or "import axcore_pkg" in text:
        raise SystemExit(f"unhandled aXcore package reference in {source}")
    parts.append(f"\n// ---- {source} ----\n{text}\n")

output = Path(sys.argv[1])
output.parent.mkdir(parents=True, exist_ok=True)
output.write_text("".join(parts))
