#!/usr/bin/env python3
"""Embed a user ELF into the kernel image as a C byte array.

The first loaded program has to reach the kernel somehow, and the filesystem
path is not wired up yet.  Embedding keeps the loader under test on its own:
if the program runs, the loader parsed a real ELF and mapped it, with no
filesystem in the loop to share the blame for a failure.

Reading it from axfs replaces this; the loader does not change when it does,
because it already takes a plain byte array.
"""
import sys

def main():
    if len(sys.argv) != 4:
        sys.exit("usage: embed_image.py IN.elf OUT.h SYMBOL")
    src, dst, symbol = sys.argv[1:]
    data = open(src, "rb").read()
    with open(dst, "w") as out:
        out.write("/* Generated by embed_image.py from %s; do not edit. */\n"
                  "#pragma once\n#include <stdint.h>\n\n" % src)
        # 4-aligned so the array itself is well placed, even though the loader
        # reads it byte-wise and does not require it.
        out.write("static const uint8_t %s[] __attribute__((aligned(4))) = {\n"
                  % symbol)
        for i in range(0, len(data), 12):
            row = ", ".join("0x%02x" % b for b in data[i:i + 12])
            out.write("  %s,\n" % row)
        out.write("};\n")
        out.write("static const uint32_t %s_size = %du;\n" % (symbol, len(data)))

if __name__ == "__main__":
    main()
